# fly.toml file generated for f1-schedule-bot on 2022-08-29T00:11:06+12:00

app = "f1-schedule-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true